language: node_js
sudo: false
node_js:
  - 11

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token:
      secure: R/O3mCF7pZGf5SVhCCHUeMd47YZq0M1g7zwtDFxZ3pmFcqvssNjl4jOmHLPBG/xwRJu9e0FWlfoP0FHySC7nUxDhXDG0TBBoP0XoGPfMmh7umb8HVfKWOI9N/oNfjn16pQBbp30FgJ3jBoAqd/u9lEVN//f0qiNaLYMJB6qQ08aVg4j8ip8HXybIuoQITIG8acMJcG7ZTUdklyzsqgco70eAmOnW8OXOYpF4kIKrUQKrMeJIF4Wc2jWpvAO/59o9GLM5sXI/fKy2U1jtUTF7i5kUKozKTYBpWfvdwsDmWaeTQcxNVzAQpmDa1h5e4u64VIw8nRxKnIh2bKPjNbx8j4SjilBLX9/XSdetukZnsadm6IosoA5FRiMFSa3cqhw9/FYGTL3lMzFIyu+HGf04yopP4kUxxRSCc5q4ZUIxXPNbajh7mgR7jGDqUwpH8tWn6wP5w/yc+fJRoxUkWpq+rKccwB85G62U3++A/+Ql85DaJtaeI7PbKhipmK6+76/sV2NqurSEs2YDZKyTfDRrykx5avTt7WtcGOpdHhGcvstrcMnQ0T7ySu/FDFpSTl48lNUWDfIacvmr32sl0Rj6xNz/Qa6lg2GocVn/F+26fSBAzTsbQO0JDBuMwS2K++m3iwMg7AsubfDC3EAXSuTt+/CMg1cdZBB78K5v0LXzH4E=
    on:
      branch: master
