language: node_js
sudo: false
node_js:
  - 11

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token:
      secure: HA8E0yRyZO96nznyBLYphhH1jHViDchNWNE62BLGwxNEenWUadqeLMxylGjaTtJ2KXKdJRREgnQ7sDL9ZwUP9wr3SCrVRpNbTAZWUssnzGCNw2QBtcMHKvI4rw76F+woYwlFRPxFZMjupfRURKXpnViDUUdizZnpSncsLBItSVK/n7vs/y7c/HjJWMo2gPQ3X9RlpHA6T2H1mZFcy9VF+nLkX6IOk1iSmgQ/xQURZ+C2Y41BrboVRmF2UxIB/IHRbI1X+at/cjATH5vywQDj9K7Y5OZ1KzvPWlu5RWkEejOhAB2UcbyFiN7jzApr0IhEvgWd/NU8Qz5LMAwPeu20hD94naeB34gT1eN2fU/AmtwhKL0jBUOZHpDb8aa2rQjeB/CsCyKCvEJR59mPVBR6M+YmQ9+OHjAmzIyiI2gas6nQYK0gSfzi8syLZY0YiYmpxUlk5W/x1WbrCbL+QP0FWh2dhyYaTBlMGjXH4e6VzhDtvtUOhKOltC1+XH6Kc+h5LrBmY9j6zIZ2dqvdT7PVBLieE0MGjbG6vV4R6YhIlgMwQ3HvuxDmlfxDYeCXkoEd4VW9R2DRheMZIPSq+zLPYdyhvwfoIIM7ugbqZf7lnT3MeBykFmLF8lOeVpMUAyfqtFa4iAObAu1RyGmziOjH8AAfR23YnxDqO1FDNclWHFs=
    on:
      branch: master
